### ISSUE TITLE
Still can vote with an empty account

### ISSUE THREAD

**Issue by nulllpc** [Koniverse/DotInsights#15]
Address: 5GRfHt5wKwb3xGvJWkGgGMbbrTPctVs6PtNGg8eJbdMt51Vj

**Comment by hieudd** [comment]
Acc has a balance on Statemine. 
![Screenshot 2022-11-19 at 12 26 56 AM](https://user-images.githubusercontent.com/2582652/202765461-8dfe8d76-8b73-49d7-91db-0b3b1ebe799a.png)
