### ISSUE TITLE
Remove projects from the ecosystem map

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/DotInsights#72]
Here is a list of projects that are not building on Polkadot anymore (as of Feb 10, 2023). Please have a look.

1. Wiv
2. Decus
3. Pawnfi
4. Insuace
5. Map protocol
6. DEXTools
7. MXC
8. Qredo
9. UniArts

**Comment by djhatrang** [comment]
Projects deleted:
1. Wiv
2. Decus
3. Pawnfi
4. Insurace
5. MAP Protocl
6. Qredo
